<a href="https://colab.research.google.com/github/gregorywmorris/MLZoom2022/blob/main/week_six/9_decision_tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework

**Exercise: Build decision tree model to predict survival based on certain parameters**

CSV file is available to download at https://github.com/codebasics/py/blob/master/ML/9_decision_tree/Exercise/titanic.csv

##### In this file using following columns build a model to predict if person would survive or not,

1. Pclass
1. Sex
1. Age
1. Fare

##### Calculate score of your model

In [56]:
data = 'https://raw.githubusercontent.com/codebasics/py/master/ML/9_decision_tree/Exercise/titanic.csv'
!wget $data

--2022-10-10 18:55:22--  https://raw.githubusercontent.com/codebasics/py/master/ML/9_decision_tree/Exercise/titanic.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 60302 (59K) [text/plain]
Saving to: ‘titanic.csv.2’

titanic.csv.2       100%[===================>]  58.89K  --.-KB/s    in 0.008s  

2022-10-10 18:55:22 (7.45 MB/s) - ‘titanic.csv.2’ saved [60302/60302]



In [68]:
import pandas as pd
import numpy as np

from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_extraction import DictVectorizer
from sklearn.metrics import roc_auc_score

In [93]:
df = pd.read_csv(data,on_bad_lines='skip')
# https://stackoverflow.com/questions/18039057/python-pandas-error-tokenizing-data

In [94]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [95]:
targets = ['Survived', 'Pclass','Sex', 'Age','Fare']

In [96]:
df = df[targets].copy()

In [97]:
df.columns = df.columns.str.lower()

In [98]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'fare'], dtype='object')

In [99]:
df.isna().sum()

survived      0
pclass        0
sex           0
age         177
fare          0
dtype: int64

In [100]:
df = df.fillna(df.age.mean())

In [101]:
df.sex = (df.sex == 'male').astype(int)

In [102]:
df.head(3)

survived  pclass  sex   age     fare
0         0       3    1  22.0   7.2500
1         1       1    0  38.0  71.2833
2         1       3    0  26.0   7.9250

In [103]:
from sklearn.model_selection import train_test_split

df_train, df_test = train_test_split(df, test_size=0.25, random_state=1)

df_train = df_train.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

y_train = (df_train.survived.values)
y_test = (df_test.survived.values)

del df_train['survived']
del df_test['survived']

In [105]:
dt = tree.DecisionTreeClassifier()

In [106]:
train_dicts = df_train.to_dict(orient='records')

dv = DictVectorizer(sparse=False)
X_train = dv.fit_transform(train_dicts)

dt.fit(X_train, y_train)



DecisionTreeClassifier()

In [107]:
test_dicts = df_test.to_dict(orient='records')

X_test = dv.transform(test_dicts)

dt.fit(X_test, y_test)

DecisionTreeClassifier()

In [108]:
y_pred = dt.predict_proba(X_test)[:, 1]
roc_auc_score(y_test, y_pred)

0.9999177631578947

In [109]:
y_pred = dt.predict_proba(X_train)[:, 1]
roc_auc_score(y_train, y_pred)

0.7200226951445854

In [111]:
dt.predict([[3,0,38,25.0]])

array([0])

In [116]:
dt.predict([[0,3,1,38,71.2833]])

array([0])

In [117]:

dt.fit(X_train,y_train)

DecisionTreeClassifier()

In [119]:
dt.score(X_test,y_test)

0.7713004484304933

In [120]:
dt.predict([[1,0,38,71.2833]])

array([1])

In [121]:
dt.predict([[3,0,38,25.0]])

array([1])

In [123]:
dt.predict([[3,1,22,7.0]])

array([1])